# 依存関係の名前解決に使用する組織名またはユーザ名
gitHubName: [TeamKUN]

#DBへのパス
dependPath: "/depend.db"

#名前解決へのパス
resolvePath: "/resolve.db"

# エイリアス定義ファイル
# 形式: JSON
# 書き方:  { "ExamplePlugin": "https://example.com/download/ExamplePlugin.jar"
config:
  - "https://raw.githubusercontent.com/TeamKun/PluginManagerRepository/main/database.json"

# 保護
ignore:
  - bStats               #削除しないでください
  - TeamKunPluginManager #削除しないでください
