# 依存関係の名前解決に使用する組織名またはユーザ名
gitHubName: TeamKUN

#OAuth token
#このキーをアップロード、公開しないでください。
oauth: ""

#DBへのパス
dependPath: "./depend.db"

#名前解決へのパス
resolvePath: "./resolve.db"

config:
  - "https://raw.githubusercontent.com/TeamKun/PluginManagerRepository/main/database.json"
