name: TeamKunPluginManager
version: ${project.version}
main: net.kunmc.lab.teamkunpluginmanager.TeamKunPluginManager
authors: [Peyang]
api-version: 1.15
description: Manage your plugin!
website: https://kunmc.net/

commands:
  kunpluginmanager:
    aliases: [p, kpm, kunpm, kunmgmt] #devicemgmt.mscへの恨み
    usage: "/kpm <install|remove> [Plugin name | URL | Repository Name]"


permissions:
  kpm.use:
    description: "このプラグインを使用できます。"
    default: op
