name: TeamKunPluginManager
version: ${project.version}
main: net.kunmc.lab.teamkunpluginmanager.TeamKunPluginManager
authors: [Peyang]
api-version: 1.15
description: Manage your plugin!
website: https://kunmc.net/

commands:
  kunpluginmanager:
    aliases: [pm, kpm, kunpm, kunmgmt] #devicemgmt.mscへの恨み
    usage: "/kpm <i|rm|info|autoremove|clean|fix|status|update|export> [Plugin name | URL | Repository Name]"


permissions:
  kpm.use:
    description: "このプラグインを使用できます。"
    default: op
    children:
      kpm.install: true
      kpm.uninstall: true
      kpm.info: true
      kpm.autoremove: true
      kpm.clean: true
      kpm.fix: true
      kpm.status: true
      kpm.update: true
      kpm.export: true
      kpm.import: true
  kpm.install:
    description: "プラグインをインストールできます。"
  kpm.uninstall:
    description: "プラグインをアンインストールします。"
  kpm.info:
    description: "プラグインの情報を閲覧します。"
  kpm.autoremove:
    description: "不要になったプラグインを削除します。"
  kpm.clean:
    description: "アンインストールされたプラグインのデータファイルを削除します。"
  kpm.fix:
    description: "プラグインのエラーを修復します。"
  kpm.status:
    description: "プラグインの状態を閲覧します。"
  kpm.update:
    description: "エイリアス定義データベースを更新します。"
  kpm.export:
    description: "プラグインとデータをエクスポートします。"
  kpm.import:
    description: "プラグインとデータをインポートします。"
