name: TeamKunPluginManager
version: ${project.version}
main: net.kunmc.lab.teamkunpluginmanager.TeamKunPluginManager
authors: [Peyang]
api-version: 1.15
description: Manage your plugin!
website: https://kunmc.net/

commands:
  kunpluginmanager:
    aliases: [pm, kpm, kunpm, kunmgmt] #devicemgmt.mscへの恨み
    usage: "/kpm <i|rm|info|autoremove|clean|fix|status|update> [Plugin name | URL | Repository Name]"


permissions:
  kpm.use:
    description: "このプラグインを使用できます。"
    default: op
