# @project      TeamKUNPluginManager
# @author       Peyang <https://peya.tokyo>
# @license      The MIT License (MIT) <https://opensource.org/licenses/MIT>


# ----------------------[ パス設定 ]---------------------
#各設定ファイルのパスを定義します。
# ------------------------------------------------------
paths:
  # 各データベースのパスです。
  # KPM では、 SQLite をデータベースとして使用しています。
  database:
    # プラグインのメタデータを保存するデータベースのパスです。
    metadata: "plugins.db"
    # プラグインのエイリアスを保存するデータベースのパスです。
    aliases: "aliases.db"

  # GitHub の API にアクセスするためのトークンを保存するファイルのパスです。
  # 注意：このファイルの権限は、他のユーザから読み取りできないように設定することをおすすめします。
  token:
    # トークンを保存するファイルの パスです。
    body: "token.dat"
    # トークンの復号鍵を保存するファイルのパスです。
    decryptionKey: "token_key.dat"

# ----------------------[ リクエスト設定 ]----------------
# HTTP リクエストの設定を定義します。
# ------------------------------------------------------
http:
  # ユーザーエージェントです。
  # %productName%      は、 KPM の名前に置換されます。      （例： TeamKUNPluginManager）
  # %productVersion%   は、 KPM のバージョンに置換されます。 （例： v1.0.0）
  userAgent: "Mozilla/8.10 (X931; Peyantu; Linux x86_64) PeyangWebKit/114.514(KUN, like Gacho) %productName%/%productVersion%"
  # タイムアウト時間です。ミリ秒で指定します。
  timeout: 10000
  # リダイレクトの最大回数です。0 にするとリダイレクトを無効化します。-1 にすると無限にリダイレクトします。
  # 注意： 無限のリダイレクトは、サーバないし KPM がハングする可能性があります。
  maxRedirects: $redirectLimit$

# ----------------------[ プラグイン解決設定 ]-------------
# プラグインの解決の設定を定義します。
# プラグイン解決とは、 インストール時等に指定するクエリから、プラグインのJarの直リンクを取得する一連の流れを指します。
# ------------------------------------------------------
resolve:
  # プラグインの解決に使用する GitHub のユーザー名です。
  # ここに指定されたユーザないし組織は、その名前を省略できます。
  # TeamKUN と指定した場合、 TeamKUN/ExamplePlugin を ExamplePlugin と指定できます。
  githubUsers: $gitHubName$

  # KPM のプラグイン解決に使用されるエイリアスの設定を定義します。
  aliases:
    # エイリアスの取得元（データソース）を定義します。
    sources: $config$

# ----------------------[ 除外設定 ]----------------------
# KPM による管理や、アンインストールやアップグレード等から除外するプラグインを定義します。
# この設定により、サーバの根幹に必要なプラグイン等々が削除されることを防ぎます。
# ------------------------------------------------------
exclude:
  # 除外するプラグインの名前を定義します。
  pluginNames: $ignore$

# ----------------------[ 製品設定 ]------------------
# これ以下は変更しないでください。
# ------------------------------------------------------

kpm: "${project.version}"
