# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [develop, stable]
  pull_request:
    branches: [develop, stable]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        id: sj
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17
          cache: maven
      - uses: PeyaPeyaPeyang/nmsaction@v3
        if: "steps.sj.outputs.cache-hit != 'true'"
        with:
          rev: 1.16.5
      - uses: PeyaPeyaPeyang/nmsaction@v3
        if: "steps.sj.outputs.cache-hit != 'true'"
        with:
          rev: 1.19
      - name: Install nms into m2
        if: "steps.sj.outputs.cache-hit != 'true'"
        run: |
          mkdir -p $HOME/.m2/repository
          cp -a nms-build/.m2/repository/. $HOME/.m2/repository
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      - name: Build with Maven
        run: mvn -B package --file pom.xml

